#compdef jm-wallet

# Static completion for jm-wallet
# Generated by scripts/generate_completions.py

_jm_wallet() {
  local -a commands
  commands=(
    'list-bonds:List all fidelity bonds in the wallet.'
    'generate-bond-address:Generate a fidelity bond (timelocked P2WSH) address.'
    'recover-bonds:Recover fidelity bonds by scanning all 960 possible timelocks.'
    'create-bond-address:Create a fidelity bond address from a public key (cold wallet workflow).'
    'generate-hot-keypair:Generate a hot wallet keypair for fidelity bond certificates.'
    'prepare-certificate-message:Prepare certificate message for signing with hardware wallet (cold wallet support).'
    'import-certificate:Import a certificate signature for a fidelity bond (cold wallet support).'
    'spend-bond:Generate a PSBT to spend a cold storage fidelity bond after locktime expires.'
    'debug-info:Print privacy-friendly diagnostic information for troubleshooting.'
    'freeze:Interactively freeze/unfreeze UTXOs to exclude them from coin selection.'
    'history:View CoinJoin transaction history.'
    'registry-show:Show detailed information about a specific fidelity bond.'
    'send:Send a simple transaction from wallet to an address.'
    'import:Import an existing BIP39 mnemonic phrase to create/recover a wallet.'
    'generate:Generate a new BIP39 mnemonic phrase with secure entropy.'
    'info:Display wallet information and balances by mixdepth.'
    'validate:Validate a mnemonic phrase.'
  )

  _arguments -C \
    '1:command:->command' \
    '*::arg:->args'

  case $state in
    command)
      _describe -t commands 'jm-wallet commands' commands
      ;;
    args)
      case $words[1] in
        list-bonds)
          _arguments \
            '--mnemonic-file=[]:file:_files' \
            '--prompt-bip39-passphrase[Prompt for BIP39 passphrase]' \
            '--network=[Bitcoin network]: :' \
            '--backend=[Backend\: scantxoutset | descriptor_wallet | neutrino]: :' \
            '--rpc-url=[]: :' \
            '--locktime=[Locktime(s) to scan for]: :' \
            '--data-dir=[Data directory (default\: ~/.joinmarket-ng or $JOINMARKET_DATA_DIR)]:file:_files' \
            '--funded-only[Show only funded bonds (offline mode)]' \
            '--active-only[Show only active bonds (offline mode)]' \
            '--json[Output as JSON (offline mode)]' \
            '--log-level=[Log level]: :' \
            '--help[Show this message and exit]'
          ;;
        generate-bond-address)
          _arguments \
            '--mnemonic-file=[]:file:_files' \
            '--prompt-bip39-passphrase[Prompt for BIP39 passphrase]' \
            '--locktime=[Locktime as Unix timestamp]: :' \
            '--locktime-date=[Locktime as YYYY-MM (must be 1st of month)]: :' \
            '--index=[Address index]: :' \
            '--network=[]: :' \
            '--data-dir=[Data directory (default\: ~/.joinmarket-ng or $JOINMARKET_DATA_DIR)]:file:_files' \
            '--no-save[Do not save the bond to the registry]' \
            '--log-level=[Log level]: :' \
            '--help[Show this message and exit]'
          ;;
        recover-bonds)
          _arguments \
            '--mnemonic-file=[]:file:_files' \
            '--prompt-bip39-passphrase[Prompt for BIP39 passphrase]' \
            '--network=[Bitcoin network]: :' \
            '--backend=[Backend\: scantxoutset | descriptor_wallet | neutrino]: :' \
            '--rpc-url=[]: :' \
            '--neutrino-url=[]: :' \
            '--max-index=[Max address index per locktime to scan (default 1)]: :' \
            '--data-dir=[Data directory (default\: ~/.joinmarket-ng or $JOINMARKET_DATA_DIR)]:file:_files' \
            '--log-level=[Log level]: :' \
            '--help[Show this message and exit]'
          ;;
        create-bond-address)
          _arguments \
            '--locktime=[Locktime as Unix timestamp]: :' \
            '--locktime-date=[Locktime as date (YYYY-MM, must be 1st of month)]: :' \
            '--network=[]: :' \
            '--data-dir=[Data directory (default\: ~/.joinmarket-ng or $JOINMARKET_DATA_DIR)]:file:_files' \
            '--no-save[Do not save the bond to the registry]' \
            '--log-level=[]: :' \
            '--help[Show this message and exit]'
          ;;
        generate-hot-keypair)
          _arguments \
            '--bond-address=[Bond address to associate keypair with (saves to registry)]: :' \
            '--data-dir=[Data directory (default\: ~/.joinmarket-ng or $JOINMARKET_DATA_DIR)]:file:_files' \
            '--log-level=[]: :' \
            '--help[Show this message and exit]'
          ;;
        prepare-certificate-message)
          _arguments \
            '--cert-pubkey=[Certificate public key (hex)]: :' \
            '--validity-periods=[Certificate validity in 2016-block periods from now (1=~2wk, 52=~2yr)]: :' \
            '--data-dir=[Data directory (default\: ~/.joinmarket-ng or $JOINMARKET_DATA_DIR)]:file:_files' \
            '--network=[Bitcoin network]: :' \
            '--backend=[Backend\: scantxoutset | descriptor_wallet | neutrino]: :' \
            '--rpc-url=[]: :' \
            '--neutrino-url=[]: :' \
            '--mempool-api=[Mempool API URL for fetching block height. Only used when no Bitcoin node backend is configured. Example\: http\://localhost\:8999/api]: :' \
            '--current-block=[Current block height override for offline/air-gapped workflows. Skips all network block-height lookups.]: :' \
            '--log-level=[]: :' \
            '--help[Show this message and exit]'
          ;;
        import-certificate)
          _arguments \
            '--cert-pubkey=[Certificate pubkey (hex)]: :' \
            '--cert-signature=[Certificate signature (base64)]: :' \
            '--cert-expiry=[Certificate expiry as ABSOLUTE period number (from prepare-certificate-message)]: :' \
            '--data-dir=[Data directory (default\: ~/.joinmarket-ng or $JOINMARKET_DATA_DIR)]:file:_files' \
            '--skip-verification[Skip signature verification (not recommended)]' \
            '--network=[Bitcoin network]: :' \
            '--backend=[Backend\: scantxoutset | descriptor_wallet | neutrino]: :' \
            '--rpc-url=[]: :' \
            '--neutrino-url=[]: :' \
            '--mempool-api=[Mempool API URL for validating cert expiry. Only used when no Bitcoin node backend is configured. Example\: http\://localhost\:8999/api]: :' \
            '--current-block=[Current block height override for offline/air-gapped workflows. Skips all network block-height lookups.]: :' \
            '--log-level=[]: :' \
            '--help[Show this message and exit]'
          ;;
        spend-bond)
          _arguments \
            '--fee-rate=[Fee rate in sat/vB]: :' \
            '--master-fingerprint=[Master key fingerprint (4 bytes hex, e.g. '\''aabbccdd'\''). Found in Sparrow\: Settings -> Keystore -> Master fingerprint. Enables Sparrow and HWI to identify the signing key.]: :' \
            '--derivation-path=[BIP32 derivation path of the key used for the bond (e.g. "m/84'\''/0'\''/0'\''/0/0"). This is the path of the address whose pubkey was used in '\''create-bond-address'\''. Check Sparrow\: Addresses tab -> right-click the address -> Copy -> Derivation Path.]: :' \
            '--output=[Save PSBT to file (default\: stdout only)]:file:_files' \
            '--test-unfunded[Allow generating a test PSBT even when the bond is unfunded, using a synthetic UTXO for signer compatibility testing.]' \
            '--test-utxo-value=[Synthetic UTXO value in sats when using --test-unfunded (default\: 100000).]: :' \
            '--data-dir=[Data directory (default\: ~/.joinmarket-ng or $JOINMARKET_DATA_DIR)]:file:_files' \
            '--log-level=[]: :' \
            '--help[Show this message and exit]'
          ;;
        debug-info)
          _arguments \
            '--network=[Bitcoin network]: :' \
            '--backend=[Backend\: scantxoutset | descriptor_wallet | neutrino]: :' \
            '--neutrino-url=[]: :' \
            '--log-level=[Log level]: :' \
            '--help[Show this message and exit]'
          ;;
        freeze)
          _arguments \
            '--mnemonic-file=[Path to mnemonic file]:file:_files' \
            '--prompt-bip39-passphrase[Prompt for BIP39 passphrase interactively]' \
            '--network=[Bitcoin network]: :' \
            '--backend=[Backend\: scantxoutset | descriptor_wallet | neutrino]: :' \
            '--rpc-url=[]: :' \
            '--neutrino-url=[]: :' \
            '--mixdepth=[Filter to a specific mixdepth (0-4)]: :' \
            '--data-dir=[Data directory (default\: ~/.joinmarket-ng or $JOINMARKET_DATA_DIR)]:file:_files' \
            '--log-level=[Log level]: :' \
            '--help[Show this message and exit]'
          ;;
        history)
          _arguments \
            '--limit=[Max entries to show]: :' \
            '--role=[Filter by role (maker/taker)]: :' \
            '--stats[Show statistics only]' \
            '--csv[Output as CSV]' \
            '--data-dir=[Data directory (default\: ~/.joinmarket-ng or $JOINMARKET_DATA_DIR)]:file:_files' \
            '--help[Show this message and exit]'
          ;;
        registry-show)
          _arguments \
            '--data-dir=[Data directory (default\: ~/.joinmarket-ng or $JOINMARKET_DATA_DIR)]:file:_files' \
            '--json[Output as JSON]' \
            '--log-level=[]: :' \
            '--help[Show this message and exit]'
          ;;
        send)
          _arguments \
            '--amount=[Amount in sats (0 for sweep)]: :' \
            '--mnemonic-file=[]:file:_files' \
            '--prompt-bip39-passphrase[Prompt for BIP39 passphrase]' \
            '--mixdepth=[Source mixdepth]: :' \
            '--fee-rate=[Manual fee rate in sat/vB (e.g. 1.5). Mutually exclusive with --block-target. Defaults to 3-block estimation.]: :' \
            '--block-target=[Target blocks for fee estimation (1-1008). Defaults to 3.]: :' \
            '--network=[Bitcoin network]: :' \
            '--backend=[Backend\: scantxoutset | descriptor_wallet | neutrino]: :' \
            '--rpc-url=[]: :' \
            '--neutrino-url=[]: :' \
            '--broadcast[Broadcast the transaction]' \
            '--yes[Skip confirmation prompt]' \
            '--select-utxos[Interactively select UTXOs (fzf-like TUI)]' \
            '--data-dir=[Data directory (default\: ~/.joinmarket-ng or $JOINMARKET_DATA_DIR)]:file:_files' \
            '--log-level=[Log level]: :' \
            '--help[Show this message and exit]'
          ;;
        import)
          _arguments \
            '--words=[Number of words (12, 15, 18, 21, or 24)]: :' \
            '--output=[Output file path]:file:_files' \
            '--prompt-password[Prompt for password interactively (default\: prompt)]' \
            '--force[Overwrite existing file without confirmation]' \
            '--help[Show this message and exit]'
          ;;
        generate)
          _arguments \
            '--words=[Number of words (12, 15, 18, 21, or 24)]: :' \
            '--save[Save to file (default\: save)]' \
            '--output=[Output file path]:file:_files' \
            '--prompt-password[Prompt for password interactively (default\: prompt)]' \
            '--help[Show this message and exit]'
          ;;
        info)
          _arguments \
            '--mnemonic-file=[Path to mnemonic file]:file:_files' \
            '--prompt-bip39-passphrase[Prompt for BIP39 passphrase interactively]' \
            '--network=[Bitcoin network]: :' \
            '--backend=[Backend\: scantxoutset | descriptor_wallet | neutrino]: :' \
            '--rpc-url=[]: :' \
            '--neutrino-url=[]: :' \
            '--extended[Show detailed address view with derivations]' \
            '--gap=[Max address gap to show in extended view]: :' \
            '--data-dir=[Data directory (default\: ~/.joinmarket-ng or $JOINMARKET_DATA_DIR)]:file:_files' \
            '--log-level=[Log level]: :' \
            '--help[Show this message and exit]'
          ;;
        validate)
          _arguments \
            '--mnemonic-file=[Path to mnemonic file]:file:_files' \
            '--help[Show this message and exit]'
          ;;
      esac
      ;;
  esac
}

compdef _jm_wallet jm-wallet
