# Static completion for jm-wallet
# Generated by scripts/generate_completions.py

_jm_wallet_completion() {
    local cur prev subcmd
    COMPREPLY=()
    cur="${COMP_WORDS[COMP_CWORD]}"
    prev="${COMP_WORDS[COMP_CWORD-1]}"

    if [ "$COMP_CWORD" -eq 1 ]; then
        COMPREPLY=( $(compgen -W "list-bonds generate-bond-address recover-bonds create-bond-address generate-hot-keypair prepare-certificate-message import-certificate spend-bond debug-info freeze history registry-show send import generate info validate" -- "$cur") )
        return 0
    fi

    subcmd="${COMP_WORDS[1]}"
    case "$subcmd" in
      list-bonds)
        COMPREPLY=( $(compgen -W "--help --mnemonic-file -f --prompt-bip39-passphrase --network -n --backend -b --rpc-url --locktime -L --data-dir --funded-only --active-only --json -j --log-level -l" -- "$cur") )
        ;;
      generate-bond-address)
        COMPREPLY=( $(compgen -W "--help --mnemonic-file -f --prompt-bip39-passphrase --locktime -L --locktime-date -d --index -i --network -n --data-dir --no-save --log-level -l" -- "$cur") )
        ;;
      recover-bonds)
        COMPREPLY=( $(compgen -W "--help --mnemonic-file -f --prompt-bip39-passphrase --network -n --backend -b --rpc-url --neutrino-url --max-index -i --data-dir --log-level -l" -- "$cur") )
        ;;
      create-bond-address)
        COMPREPLY=( $(compgen -W "--help --locktime -L --locktime-date -d --network -n --data-dir --no-save --log-level -l" -- "$cur") )
        ;;
      generate-hot-keypair)
        COMPREPLY=( $(compgen -W "--help --bond-address --data-dir --log-level" -- "$cur") )
        ;;
      prepare-certificate-message)
        COMPREPLY=( $(compgen -W "--help --cert-pubkey --validity-periods --data-dir --network -n --backend -b --rpc-url --neutrino-url --mempool-api --current-block --log-level" -- "$cur") )
        ;;
      import-certificate)
        COMPREPLY=( $(compgen -W "--help --cert-pubkey --cert-signature --cert-expiry --data-dir --skip-verification --network -n --backend -b --rpc-url --neutrino-url --mempool-api --current-block --log-level" -- "$cur") )
        ;;
      spend-bond)
        COMPREPLY=( $(compgen -W "--help --fee-rate -f --master-fingerprint -m --derivation-path -p --output -o --test-unfunded --test-utxo-value --data-dir --log-level -l" -- "$cur") )
        ;;
      debug-info)
        COMPREPLY=( $(compgen -W "--help --network -n --backend -b --neutrino-url --log-level -l" -- "$cur") )
        ;;
      freeze)
        COMPREPLY=( $(compgen -W "--help --mnemonic-file -f --prompt-bip39-passphrase --network -n --backend -b --rpc-url --neutrino-url --mixdepth -m --data-dir --log-level -l" -- "$cur") )
        ;;
      history)
        COMPREPLY=( $(compgen -W "--help --limit -n --role -r --stats -s --csv --data-dir" -- "$cur") )
        ;;
      registry-show)
        COMPREPLY=( $(compgen -W "--help --data-dir --json -j --log-level -l" -- "$cur") )
        ;;
      send)
        COMPREPLY=( $(compgen -W "--help --amount -a --mnemonic-file -f --prompt-bip39-passphrase --mixdepth -m --fee-rate --block-target --network -n --backend -b --rpc-url --neutrino-url --broadcast --yes -y --select-utxos -s --data-dir --log-level -l" -- "$cur") )
        ;;
      import)
        COMPREPLY=( $(compgen -W "--help --words -w --output -o --prompt-password --force -f" -- "$cur") )
        ;;
      generate)
        COMPREPLY=( $(compgen -W "--help --words -w --save --output -o --prompt-password" -- "$cur") )
        ;;
      info)
        COMPREPLY=( $(compgen -W "--help --mnemonic-file -f --prompt-bip39-passphrase --network -n --backend -b --rpc-url --neutrino-url --extended -e --gap -g --data-dir --log-level -l" -- "$cur") )
        ;;
      validate)
        COMPREPLY=( $(compgen -W "--help --mnemonic-file -f" -- "$cur") )
        ;;
    esac
    return 0
}

complete -o default -F _jm_wallet_completion jm-wallet
